CREATE TABLE IF NOT EXISTS games (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    genre VARCHAR(100) NOT NULL,
    platform VARCHAR(100) NOT NULL,
    play_style VARCHAR(100) NOT NULL,
    streamability_score INT NOT NULL,
    webcam_fit_score INT NOT NULL,
    tts_fit_score INT NOT NULL,
    stt_fit_score INT NOT NULL,
    novelty_score INT NOT NULL,
    dev_feasibility_score INT NOT NULL,
    market_signal_score INT NOT NULL,
    recommendation_score DOUBLE PRECISION NOT NULL,
    reason TEXT,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS onboarding_analysis_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT,
    parent_history_id BIGINT,
    conversation_id VARCHAR(100),
    message VARCHAR(2000) NOT NULL,
    target_platform VARCHAR(100),
    team_size VARCHAR(100),
    preferred_features_json TEXT NOT NULL,
    development_period VARCHAR(100),
    summary VARCHAR(1000) NOT NULL,
    recommended_concepts_json TEXT NOT NULL,
    report TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS conversation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    session_id VARCHAR(100) NOT NULL,
    title VARCHAR(200) NOT NULL,
    last_message VARCHAR(500),
    last_intent VARCHAR(80),
    status VARCHAR(40) NOT NULL DEFAULT 'ACTIVE',
    hidden_at TIMESTAMP,
    hidden_by_user_id BIGINT,
    deleted_at TIMESTAMP,
    deleted_by_user_id BIGINT,
    moderation_reason TEXT,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS conversation_message (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id BIGINT NOT NULL,
    role VARCHAR(40) NOT NULL,
    content TEXT NOT NULL,
    intent VARCHAR(80),
    evidence_json TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS conversation_memory_summary (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id VARCHAR(100) NOT NULL UNIQUE,
    project_id BIGINT,
    conversation_id BIGINT,
    current_user_goal VARCHAR(500),
    last_intent VARCHAR(80),
    last_user_role VARCHAR(80),
    preferred_platform VARCHAR(80),
    preferred_sort_metric VARCHAR(80),
    mentioned_games_json TEXT NOT NULL,
    recommended_games_json TEXT NOT NULL,
    developer_candidates_json TEXT NOT NULL,
    reinterpretation_candidates_json TEXT NOT NULL,
    interaction_features_json TEXT NOT NULL,
    constraints_json TEXT NOT NULL,
    excluded_json TEXT NOT NULL,
    summary_text TEXT,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(320) UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    nickname VARCHAR(100) NOT NULL,
    role VARCHAR(40) NOT NULL,
    provider VARCHAR(40),
    provider_id VARCHAR(120),
    profile_image_url VARCHAR(1000),
    email_verified BOOLEAN NOT NULL DEFAULT FALSE,
    auth_type VARCHAR(40) NOT NULL DEFAULT 'LOCAL',
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    UNIQUE (provider, provider_id)
);

CREATE TABLE IF NOT EXISTS user_project (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    title VARCHAR(200) NOT NULL,
    description TEXT,
    project_type VARCHAR(80) NOT NULL,
    target_audience VARCHAR(200),
    preferred_platform VARCHAR(100),
    interaction_features_json TEXT NOT NULL,
    status VARCHAR(40) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS trend_game (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    genre VARCHAR(100) NOT NULL,
    platform VARCHAR(100) NOT NULL,
    steam_app_id INT,
    twitch_keyword VARCHAR(200),
    steam_review_score INT NOT NULL,
    steam_total_reviews INT NOT NULL,
    steam_positive_rate DOUBLE PRECISION NOT NULL,
    twitch_live_stream_count INT NOT NULL,
    twitch_total_viewer_count INT NOT NULL,
    twitch_viewer_score INT NOT NULL,
    twitch_stream_count_score INT NOT NULL,
    streamability_score INT NOT NULL,
    market_signal_score INT NOT NULL,
    internal_recommendation_score DOUBLE PRECISION NOT NULL,
    trend_score DOUBLE PRECISION NOT NULL,
    signal_status VARCHAR(80) NOT NULL,
    reason TEXT,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS live_trend_game (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source VARCHAR(40) NOT NULL,
    title VARCHAR(200) NOT NULL,
    genre VARCHAR(100) NOT NULL,
    platform VARCHAR(100) NOT NULL,
    source_keyword VARCHAR(200),
    live_stream_count INT NOT NULL,
    total_viewer_count INT NOT NULL,
    viewer_score INT NOT NULL,
    stream_count_score INT NOT NULL,
    streamability_score INT NOT NULL,
    market_signal_score INT NOT NULL,
    trend_score DOUBLE PRECISION NOT NULL,
    signal_status VARCHAR(80) NOT NULL,
    data_origin VARCHAR(80) NOT NULL DEFAULT 'FALLBACK',
    reason TEXT,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS live_trend_refresh_status (
    id BIGINT PRIMARY KEY,
    running BOOLEAN NOT NULL,
    last_refresh_started_at TIMESTAMP,
    last_refresh_completed_at TIMESTAMP,
    last_refresh_status VARCHAR(80) NOT NULL,
    last_refresh_message TEXT,
    next_refresh_estimate TIMESTAMP,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS live_trend_platform_status (
    id BIGINT PRIMARY KEY,
    platform VARCHAR(40) NOT NULL UNIQUE,
    configured BOOLEAN NOT NULL,
    status VARCHAR(80) NOT NULL,
    message TEXT,
    last_success_at TIMESTAMP,
    last_failure_at TIMESTAMP,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS legacy_game (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    source VARCHAR(40) NOT NULL,
    source_game_id VARCHAR(80) NOT NULL,
    steam_app_id INT,
    release_year INT NOT NULL,
    genres_json TEXT NOT NULL,
    tags_json TEXT NOT NULL,
    mechanics_json TEXT NOT NULL,
    interaction_hints_json TEXT NOT NULL,
    mechanic_uniqueness_score INT NOT NULL,
    streamability_score INT NOT NULL,
    interaction_fit_seed_score INT NOT NULL,
    dev_feasibility_score INT NOT NULL,
    review_count INT NOT NULL,
    positive_review_rate DOUBLE PRECISION NOT NULL,
    legacy_popularity_score INT NOT NULL,
    review_sentiment_score INT NOT NULL,
    data_origin VARCHAR(80) NOT NULL,
    reason TEXT,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    UNIQUE (source, source_game_id)
);

CREATE TABLE IF NOT EXISTS game_reinterpretation_candidate (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    legacy_game_id BIGINT NOT NULL,
    title VARCHAR(200) NOT NULL,
    source VARCHAR(40) NOT NULL,
    source_game_id VARCHAR(80) NOT NULL,
    steam_app_id INT,
    release_year INT NOT NULL,
    genres_json TEXT NOT NULL,
    tags_json TEXT NOT NULL,
    mechanics_json TEXT NOT NULL,
    interaction_hints_json TEXT NOT NULL,
    legacy_popularity_score INT NOT NULL,
    review_sentiment_score INT NOT NULL,
    mechanic_uniqueness_score INT NOT NULL,
    streamability_score INT NOT NULL,
    interaction_fit_score INT NOT NULL,
    modern_trend_fit_score INT NOT NULL,
    dev_feasibility_score INT NOT NULL,
    reinterpretation_score DOUBLE PRECISION NOT NULL,
    reinterpretation_concept VARCHAR(300) NOT NULL,
    reason TEXT,
    data_origin VARCHAR(80) NOT NULL,
    review_count INT NOT NULL,
    positive_review_rate DOUBLE PRECISION NOT NULL,
    matched_live_trend_sources_json TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    UNIQUE (legacy_game_id)
);

ALTER TABLE users ADD COLUMN IF NOT EXISTS phone_number VARCHAR(30);
ALTER TABLE users ADD COLUMN IF NOT EXISTS phone_verified BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS status VARCHAR(40) NOT NULL DEFAULT 'ACTIVE';
ALTER TABLE users ADD COLUMN IF NOT EXISTS last_login_at TIMESTAMP;
ALTER TABLE users ADD COLUMN IF NOT EXISTS failed_login_count INT NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS locked_until TIMESTAMP;
ALTER TABLE users ADD COLUMN IF NOT EXISTS chat_restricted_until TIMESTAMP;
ALTER TABLE users ADD COLUMN IF NOT EXISTS chat_restriction_reason TEXT;

ALTER TABLE onboarding_analysis_history ADD COLUMN IF NOT EXISTS user_id BIGINT;

ALTER TABLE conversation ADD COLUMN IF NOT EXISTS status VARCHAR(40) NOT NULL DEFAULT 'ACTIVE';
ALTER TABLE conversation ADD COLUMN IF NOT EXISTS hidden_at TIMESTAMP;
ALTER TABLE conversation ADD COLUMN IF NOT EXISTS hidden_by_user_id BIGINT;
ALTER TABLE conversation ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMP;
ALTER TABLE conversation ADD COLUMN IF NOT EXISTS deleted_by_user_id BIGINT;
ALTER TABLE conversation ADD COLUMN IF NOT EXISTS moderation_reason TEXT;

CREATE TABLE IF NOT EXISTS phone_verifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phone_number VARCHAR(30) NOT NULL,
    code_hash VARCHAR(255) NOT NULL,
    purpose VARCHAR(40) NOT NULL DEFAULT 'REGISTER',
    status VARCHAR(40) NOT NULL DEFAULT 'PENDING',
    attempt_count INT NOT NULL DEFAULT 0,
    resend_count INT NOT NULL DEFAULT 0,
    last_sent_at TIMESTAMP NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    verified_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS admin_approval_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    requester_email VARCHAR(320) NOT NULL,
    requester_nickname VARCHAR(100) NOT NULL,
    requester_phone_number VARCHAR(30),
    status VARCHAR(40) NOT NULL DEFAULT 'PENDING',
    token_hash VARCHAR(255) NOT NULL UNIQUE,
    token_expires_at TIMESTAMP NOT NULL,
    approval_email_sent_to VARCHAR(320) NOT NULL,
    request_reason TEXT,
    decision_reason TEXT,
    approved_by_user_id BIGINT,
    rejected_by_user_id BIGINT,
    requested_at TIMESTAMP NOT NULL,
    approved_at TIMESTAMP,
    rejected_at TIMESTAMP,
    used_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS admin_audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admin_user_id BIGINT,
    action VARCHAR(80) NOT NULL,
    target_type VARCHAR(80) NOT NULL,
    target_id BIGINT,
    ip_address VARCHAR(80),
    user_agent VARCHAR(1000),
    detail TEXT,
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS chats (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    conversation_id BIGINT,
    conversation_message_id BIGINT,
    role VARCHAR(40) NOT NULL,
    content TEXT NOT NULL,
    status VARCHAR(40) NOT NULL DEFAULT 'ACTIVE',
    reported BOOLEAN NOT NULL DEFAULT FALSE,
    hidden_at TIMESTAMP,
    hidden_by_user_id BIGINT,
    deleted_at TIMESTAMP,
    deleted_by_user_id BIGINT,
    moderation_reason TEXT,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS chat_reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chat_id BIGINT NOT NULL,
    reporter_user_id BIGINT,
    reason VARCHAR(300) NOT NULL,
    detail TEXT,
    status VARCHAR(40) NOT NULL DEFAULT 'PENDING',
    handled_by_user_id BIGINT,
    handled_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS chat_moderation_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chat_id BIGINT,
    admin_user_id BIGINT,
    action VARCHAR(80) NOT NULL,
    reason TEXT,
    ip_address VARCHAR(80),
    user_agent VARCHAR(1000),
    detail TEXT,
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS youtube_videos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    video_id VARCHAR(80) NOT NULL UNIQUE,
    game_keyword VARCHAR(200) NOT NULL,
    keyword VARCHAR(200),
    title VARCHAR(500) NOT NULL,
    description TEXT,
    published_at TIMESTAMP,
    channel_id VARCHAR(80),
    channel_title VARCHAR(300),
    thumbnail_url VARCHAR(1000),
    view_count BIGINT NOT NULL DEFAULT 0,
    like_count BIGINT NOT NULL DEFAULT 0,
    comment_count BIGINT NOT NULL DEFAULT 0,
    duration_seconds BIGINT NOT NULL DEFAULT 0,
    collected_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS youtube_collect_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    keyword VARCHAR(200) NOT NULL,
    status VARCHAR(40) NOT NULL,
    message TEXT,
    video_count INT NOT NULL DEFAULT 0,
    score_count INT NOT NULL DEFAULT 0,
    started_at TIMESTAMP NOT NULL,
    completed_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS youtube_comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    comment_id VARCHAR(120) NOT NULL UNIQUE,
    video_id VARCHAR(80) NOT NULL,
    game_keyword VARCHAR(255) NOT NULL,
    author_name VARCHAR(300),
    text TEXT,
    like_count BIGINT NOT NULL DEFAULT 0,
    published_at TIMESTAMP,
    collected_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS youtube_keyword_stats (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_keyword VARCHAR(200) NOT NULL,
    stat_keyword VARCHAR(100) NOT NULL,
    sentiment VARCHAR(20) NOT NULL,
    mention_count INT NOT NULL DEFAULT 0,
    sample_text TEXT,
    collected_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    UNIQUE (game_keyword, stat_keyword, sentiment)
);

CREATE TABLE IF NOT EXISTS game_youtube_trend_scores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_id BIGINT,
    keyword VARCHAR(200) NOT NULL UNIQUE,
    game_title VARCHAR(300) NOT NULL,
    total_view_count BIGINT NOT NULL DEFAULT 0,
    average_view_count DOUBLE PRECISION NOT NULL DEFAULT 0,
    total_like_count BIGINT NOT NULL DEFAULT 0,
    total_comment_count BIGINT NOT NULL DEFAULT 0,
    average_engagement_rate DOUBLE PRECISION NOT NULL DEFAULT 0,
    video_count INT NOT NULL DEFAULT 0,
    view_score DOUBLE PRECISION NOT NULL DEFAULT 0,
    engagement_score DOUBLE PRECISION NOT NULL DEFAULT 0,
    volume_score DOUBLE PRECISION NOT NULL DEFAULT 0,
    youtube_interest_score DOUBLE PRECISION NOT NULL DEFAULT 0,
    collected_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

ALTER TABLE youtube_videos ADD COLUMN IF NOT EXISTS game_keyword VARCHAR(200);
ALTER TABLE youtube_videos ADD COLUMN IF NOT EXISTS keyword VARCHAR(200);
ALTER TABLE youtube_comments ADD COLUMN IF NOT EXISTS game_keyword VARCHAR(255) DEFAULT 'UNKNOWN';
ALTER TABLE youtube_comments ADD COLUMN IF NOT EXISTS author_name VARCHAR(300);
ALTER TABLE youtube_comments ADD COLUMN IF NOT EXISTS text TEXT;
ALTER TABLE youtube_comments ADD COLUMN IF NOT EXISTS like_count BIGINT NOT NULL DEFAULT 0;
ALTER TABLE youtube_comments ADD COLUMN IF NOT EXISTS published_at TIMESTAMP;
ALTER TABLE youtube_comments ADD COLUMN IF NOT EXISTS collected_at TIMESTAMP;
UPDATE youtube_comments SET game_keyword = 'UNKNOWN' WHERE game_keyword IS NULL;
ALTER TABLE youtube_comments ALTER COLUMN game_keyword VARCHAR(255);
ALTER TABLE youtube_comments ALTER COLUMN game_keyword SET NOT NULL;
ALTER TABLE youtube_keyword_stats ADD COLUMN IF NOT EXISTS game_keyword VARCHAR(200);
ALTER TABLE youtube_keyword_stats ADD COLUMN IF NOT EXISTS stat_keyword VARCHAR(100);
ALTER TABLE youtube_keyword_stats ADD COLUMN IF NOT EXISTS sentiment VARCHAR(20);
ALTER TABLE youtube_keyword_stats ADD COLUMN IF NOT EXISTS mention_count INT NOT NULL DEFAULT 0;
ALTER TABLE youtube_keyword_stats ADD COLUMN IF NOT EXISTS sample_text TEXT;
ALTER TABLE youtube_keyword_stats ADD COLUMN IF NOT EXISTS collected_at TIMESTAMP;
ALTER TABLE youtube_keyword_stats ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP;
ALTER TABLE game_youtube_trend_scores ADD COLUMN IF NOT EXISTS average_engagement_rate DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE game_youtube_trend_scores ADD COLUMN IF NOT EXISTS volume_score DOUBLE PRECISION NOT NULL DEFAULT 0;

CREATE INDEX IF NOT EXISTS idx_users_role ON users (role);
CREATE INDEX IF NOT EXISTS idx_users_status ON users (status);
CREATE INDEX IF NOT EXISTS idx_users_phone_number ON users (phone_number);
CREATE INDEX IF NOT EXISTS idx_users_last_login_at ON users (last_login_at);

CREATE INDEX IF NOT EXISTS idx_onboarding_analysis_history_user_created_at
    ON onboarding_analysis_history (user_id, created_at);

CREATE INDEX IF NOT EXISTS idx_conversation_user_status_updated_at ON conversation (user_id, status, updated_at);
CREATE INDEX IF NOT EXISTS idx_conversation_status_updated_at ON conversation (status, updated_at);

CREATE INDEX IF NOT EXISTS idx_phone_verifications_phone_status ON phone_verifications (phone_number, status);
CREATE INDEX IF NOT EXISTS idx_phone_verifications_expires_at ON phone_verifications (expires_at);
CREATE INDEX IF NOT EXISTS idx_phone_verifications_last_sent_at ON phone_verifications (last_sent_at);

CREATE INDEX IF NOT EXISTS idx_admin_approval_requests_user_status ON admin_approval_requests (user_id, status);
CREATE INDEX IF NOT EXISTS idx_admin_approval_requests_status ON admin_approval_requests (status);
CREATE INDEX IF NOT EXISTS idx_admin_approval_requests_token_expires_at ON admin_approval_requests (token_expires_at);
CREATE INDEX IF NOT EXISTS idx_admin_approval_requests_requested_at ON admin_approval_requests (requested_at);

CREATE INDEX IF NOT EXISTS idx_admin_audit_logs_admin_created_at ON admin_audit_logs (admin_user_id, created_at);
CREATE INDEX IF NOT EXISTS idx_admin_audit_logs_action_created_at ON admin_audit_logs (action, created_at);
CREATE INDEX IF NOT EXISTS idx_admin_audit_logs_target ON admin_audit_logs (target_type, target_id);

CREATE INDEX IF NOT EXISTS idx_chats_user_created_at ON chats (user_id, created_at);
CREATE INDEX IF NOT EXISTS idx_chats_status_created_at ON chats (status, created_at);
CREATE INDEX IF NOT EXISTS idx_chats_reported ON chats (reported);
CREATE INDEX IF NOT EXISTS idx_chats_conversation_id ON chats (conversation_id);

CREATE INDEX IF NOT EXISTS idx_chat_reports_chat_id ON chat_reports (chat_id);
CREATE INDEX IF NOT EXISTS idx_chat_reports_status_created_at ON chat_reports (status, created_at);
CREATE INDEX IF NOT EXISTS idx_chat_reports_reporter_user_id ON chat_reports (reporter_user_id);

CREATE INDEX IF NOT EXISTS idx_chat_moderation_logs_chat_created_at ON chat_moderation_logs (chat_id, created_at);
CREATE INDEX IF NOT EXISTS idx_chat_moderation_logs_admin_created_at ON chat_moderation_logs (admin_user_id, created_at);

CREATE INDEX IF NOT EXISTS idx_youtube_videos_keyword_collected_at ON youtube_videos (game_keyword, collected_at);
CREATE INDEX IF NOT EXISTS idx_youtube_videos_channel_id ON youtube_videos (channel_id);
CREATE INDEX IF NOT EXISTS idx_youtube_comments_video_id ON youtube_comments (video_id);
CREATE INDEX IF NOT EXISTS idx_youtube_comments_game_keyword ON youtube_comments (game_keyword);
CREATE INDEX IF NOT EXISTS idx_youtube_keyword_stats_game_sentiment ON youtube_keyword_stats (game_keyword, sentiment);
CREATE INDEX IF NOT EXISTS idx_youtube_collect_logs_keyword_started_at ON youtube_collect_logs (keyword, started_at);
CREATE INDEX IF NOT EXISTS idx_youtube_collect_logs_status_started_at ON youtube_collect_logs (status, started_at);
CREATE INDEX IF NOT EXISTS idx_game_youtube_scores_score ON game_youtube_trend_scores (youtube_interest_score);
CREATE INDEX IF NOT EXISTS idx_game_youtube_scores_game_id ON game_youtube_trend_scores (game_id);
